"""Text-analysis sources (docs/research/text_analysis.md, the mix's "analysis" block): authorship (human / AI, which model
family), formality, sentiment, emotion, offensiveness. EN + FR.

Same contract as ``sources.py``: each adapter maps one row to item dicts. Where several
annotators rated a text, the target is their distribution (soft), never its argmax.
Loading details (script-only repos, the 11.8 GB RAID CSV) were verified against the Hub
on 2026-09-29 with ``datasets`` 4.x, which no longer runs loading scripts.
"""

from __future__ import annotations

import re
from collections import defaultdict

import numpy as np

from tjev.data.sources.base import CACHE, Source

# --- authorship ------------------------------------------------------------------------

AUTHOR_TEXT = {
    "noul": "Was this text generated by an AI language model?",
    "false": "Written by a person",
    "true": "Generated by an AI model",
    "choice": "Who most likely wrote this text?",
    "families": {
        "human": "A person",
        "openai": "An OpenAI GPT model",
        "meta": "A Meta model (LLaMA, OPT)",
        "mistral": "A Mistral model",
        "cohere": "A Cohere model",
        "eleuther": "An EleutherAI model (GPT-J, GPT-NeoX, Pythia)",
        "google": "A Google T5-family model (T5, Flan-T5)",
        "bigscience": "A BigScience model (BLOOM, T0)",
        "mpt": "A MosaicML MPT model",
        "glm": "A GLM model",
    },
}

# generator name (lower-cased) → family; checked in order, first prefix match wins
_FAMILY_PREFIXES = (
    ("human", "human"),
    ("gpt_j", "eleuther"),
    ("gpt-j", "eleuther"),
    ("gptj", "eleuther"),
    ("gpt-neox", "eleuther"),
    ("gpt_neox", "eleuther"),
    ("neox", "eleuther"),
    ("pythia", "eleuther"),
    ("gpt", "openai"),
    ("chatgpt", "openai"),
    ("text-davinci", "openai"),
    ("davinci", "openai"),
    ("llama", "meta"),
    ("opt", "meta"),
    ("mistral", "mistral"),
    ("cohere", "cohere"),
    ("flan", "google"),
    ("t5", "google"),
    ("t0", "bigscience"),
    ("bloom", "bigscience"),
    ("mpt", "mpt"),
    ("glm", "glm"),
)


def model_family(name: str) -> str | None:
    name = name.lower().strip()
    for prefix, family in _FAMILY_PREFIXES:
        if name.startswith(prefix):
            return family
    return None


def _authorship(text: str, family: str | None, rng) -> list[dict]:
    """Half "AI or not?" (noul), half "which family?" (a menu of 4–6 families)."""
    human = family == "human"
    if family is None or rng.random() < 0.5:
        return [
            {
                "state": text,
                "expected": "no" if human else "yes",
                "question": {
                    "type": "noul",
                    "instructions": AUTHOR_TEXT["noul"],
                    "criteria": {"false": AUTHOR_TEXT["false"], "true": AUTHOR_TEXT["true"]},
                },
            }
        ]
    names = AUTHOR_TEXT["families"]
    pool = [n for n in names if n not in (family, "human")]
    picked = [str(n) for n in rng.choice(pool, size=int(rng.integers(3, 6)), replace=False)]
    labels = [family, *picked] + ([] if human else ["human"])
    labels = [labels[i] for i in rng.permutation(len(labels))]
    return [
        {
            "state": text,
            "expected": family,
            "question": {
                "type": "choice",
                "instructions": AUTHOR_TEXT["choice"],
                "criteria": {n: names[n] for n in labels},
            },
        }
    ]


def raid(row, rng, meta):
    """RAID: ``model`` is "human" or the generator; ``attack`` rows (paraphrase,
    homoglyphs, zero-width spaces, …) are kept as hard cases."""
    return _authorship(row["generation"], model_family(row["model"]), rng)


def mage(row, rng, meta):
    """MAGE: ``src`` = ``{domain}_{human|machine_<prompt>_<model>}``; ``label`` 1 = human."""
    src = row["src"]
    if row["label"] == 1:
        family = "human"
    else:
        m = re.search(r"_machine_(?:continuation|topical|specified)_(.+)$", src)
        family = model_family(m.group(1)) if m else None
    return _authorship(row["text"], family, rng)


def hc3_fr(row, rng, meta):
    """HC3 French (machine-translated QA): human vs ChatGPT answer to a question."""
    return [
        {
            "state": f"Question : {row['question']}\nRéponse : {row['answer']}",
            "expected": "yes" if row["label"] == "CHATGPT" else "no",
            "question": {
                "type": "noul",
                "instructions": "La réponse a-t-elle été générée par une IA ?",
                "criteria": {
                    "false": "Rédigée par une personne",
                    "true": "Générée par un modèle d'IA",
                },
            },
        }
    ]


RAID_SAMPLE = 60000
RAID_ATTACK_KEEP = 1 / 33  # attacked rows are 11/12 of RAID: keep ~25% of the sample attacked


def raid_sample(split: str):
    """A seeded reservoir sample of RAID train, streamed once (the CSV is 11.8 GB) and
    cached as parquet. Unattacked rows are all eligible, attacked ones with prob 1/33."""
    from datasets import Dataset, load_dataset

    cache = CACHE
    path = cache / f"raid-{split}-{RAID_SAMPLE}.parquet"
    if path.exists():
        return Dataset.from_parquet(str(path))
    rng = np.random.default_rng(1234)
    keep: list[dict] = []
    seen = 0
    fields = ("generation", "model", "attack", "domain", "source_id")
    for row in load_dataset("liamdugan/raid", "raid", split=split, streaming=True):
        if row["attack"] != "none" and rng.random() >= RAID_ATTACK_KEEP:
            continue
        if not row["generation"] or not row["generation"].strip():
            continue
        seen += 1
        r = {k: str(row[k]) for k in fields}
        if len(keep) < RAID_SAMPLE:
            keep.append(r)
        else:
            j = int(rng.integers(0, seen))
            if j < RAID_SAMPLE:
                keep[j] = r
    ds = Dataset.from_list(keep)
    path.parent.mkdir(parents=True, exist_ok=True)
    ds.to_parquet(str(path))
    return ds


# --- formality, sentiment, emotion, offensiveness ------------------------------------

FORMALITY_LEVELS = [
    "very informal",
    "informal",
    "neutral",
    "formal",
    "very formal",
]


def pavlick_formality(row, rng, meta):
    """Mean of 5 annotators in [-3, 3] → a soft 5-level score (interpolated, like stsb)."""
    value = (float(row["avg_score"]) + 3.0) / 6.0 * 4.0
    lo = int(np.floor(value))
    hi = min(lo + 1, 4)
    frac = value - lo
    target = {str(i): 0.0 for i in range(5)}
    target[str(lo)] += 1.0 - frac if hi != lo else 1.0
    if hi != lo:
        target[str(hi)] += frac
    return [
        {
            "state": row["sentence"],
            "target": target,
            "question": {
                "type": "score",
                "instructions": "How formal is the register of this sentence?",
                "criteria": FORMALITY_LEVELS,
            },
        }
    ]


SENTIMENT_TEXT = {
    "en": (
        "What is the overall sentiment of the text?",
        {"negative": "Negative", "neutral": "Neutral or mixed", "positive": "Positive"},
    ),
    "fr": (
        "Quel est le sentiment général du texte ?",
        {"negative": "Négatif", "neutral": "Neutre ou mitigé", "positive": "Positif"},
    ),
}


def tweet_sentiment(lang: str):
    instructions, criteria = SENTIMENT_TEXT[lang]
    names = ("negative", "neutral", "positive")

    def adapter(row, rng, meta):
        return [
            {
                "state": row["text"],
                "expected": names[row["label"]],
                "question": {"type": "choice", "instructions": instructions, "criteria": criteria},
            }
        ]

    return adapter


# GoEmotions → Ekman groups (the dataset's own ekman_mapping.json) + neutral
EKMAN = {
    "anger": ("anger", "annoyance", "disapproval"),
    "disgust": ("disgust",),
    "fear": ("fear", "nervousness"),
    "joy": (
        "joy",
        "amusement",
        "approval",
        "excitement",
        "gratitude",
        "love",
        "optimism",
        "relief",
        "pride",
        "admiration",
        "desire",
        "caring",
    ),
    "sadness": ("sadness", "disappointment", "embarrassment", "grief", "remorse"),
    "surprise": ("surprise", "realization", "confusion", "curiosity"),
    "neutral": ("neutral",),
}
EKMAN_TEXT = {
    "anger": "Anger or annoyance",
    "disgust": "Disgust",
    "fear": "Fear or nervousness",
    "joy": "Joy, amusement, gratitude or affection",
    "sadness": "Sadness or disappointment",
    "surprise": "Surprise, confusion or curiosity",
    "neutral": "No particular emotion",
}


def go_emotions_raters(split: str):
    """One row per text: the Ekman distribution averaged over its raters (a rater who
    picks several emotions spreads their vote); unclear-flagged ratings are dropped."""
    from datasets import Dataset, load_dataset

    raw = load_dataset("google-research-datasets/go_emotions", "raw", split=split)
    columns = {g: [c for c in members if c in raw.column_names] for g, members in EKMAN.items()}
    votes: dict[str, np.ndarray] = defaultdict(lambda: np.zeros(len(EKMAN)))
    text: dict[str, str] = {}
    for row in raw:
        if row["example_very_unclear"]:
            continue
        hit = np.asarray([any(row[c] for c in columns[g]) for g in EKMAN], float)
        if hit.sum() == 0:
            continue
        votes[row["id"]] += hit / hit.sum()
        text[row["id"]] = row["text"]
    rows = [
        {"id": i, "text": text[i], "dist": (v / v.sum()).round(4).tolist(), "raters": v.sum()}
        for i, v in votes.items()
        if v.sum() >= 2  # a distribution needs at least two raters
    ]
    return Dataset.from_list(rows)


def go_emotions(row, rng, meta):
    dist = np.asarray(row["dist"], float)
    return [
        {
            "state": row["text"],
            "target": {g: float(p) for g, p in zip(EKMAN, dist / dist.sum(), strict=True)},
            "question": {
                "type": "choice",
                "instructions": "Which emotion does the author mainly express?",
                "criteria": EKMAN_TEXT,
            },
        }
    ]


OFFENSIVE_TEXT = {
    "en": (
        "Is this message offensive, abusive or hateful?",
        {"false": "Not offensive", "true": "Offensive, abusive or hateful"},
    ),
    "fr": (
        "Ce message est-il offensant, injurieux ou haineux ?",
        {"false": "Pas offensant", "true": "Offensant, injurieux ou haineux"},
    ),
}


def mlma(lang: str):
    """MLMA: ``sentiment`` joins the annotators' labels (``abusive_normal`` …); the share
    of non-``normal`` labels is the soft probability of "offensive"."""
    instructions, criteria = OFFENSIVE_TEXT[lang]

    def adapter(row, rng, meta):
        labels = [x for x in str(row["sentiment"]).split("_") if x]
        if not labels or not row["tweet"].strip():
            return []
        p = sum(x != "normal" for x in labels) / len(labels)
        text = re.sub(r"@user\b", "@utilisateur" if lang == "fr" else "@user", row["tweet"])
        return [
            {
                "state": text,
                "target": {"no": 1.0 - p, "yes": p},
                "question": {"type": "noul", "instructions": instructions, "criteria": criteria},
            }
        ]

    return adapter


def textdetox(lang: str):
    instructions, criteria = OFFENSIVE_TEXT[lang]

    def adapter(row, rng, meta):
        return [
            {
                "state": row["text"],
                "expected": "yes" if int(row["toxic"]) == 1 else "no",
                "question": {"type": "noul", "instructions": instructions, "criteria": criteria},
            }
        ]

    return adapter


PARQUET = {"revision": "refs/convert/parquet"}

TEXT_SOURCES: dict[str, Source] = {
    s.name: s
    for s in [
        Source(
            "raid", "liamdugan/raid", "raid", "train", None, raid, "authorship", "en",
            "MIT", True, cap=20000, load=raid_sample, group=lambda r: r["source_id"],
        ),
        Source(
            "mage", "yaful/MAGE", None, "train", "test", mage, "authorship", "en",
            "Apache-2.0", True, cap=20000,
        ),
        Source(
            "hc3_fr", "almanach/hc3_french_ood", None, "train", "test", hc3_fr,
            "authorship", "fr", "CC BY-SA 4.0 (machine-translated HC3)", True, cap=10000,
            load_kwargs={**PARQUET, "data_dir": "hc3_fr_qa"},
        ),
        Source(
            "pavlick_formality", "osyvokon/pavlick-formality-scores", None, "train", "test",
            pavlick_formality, "style", "en", "CC BY 3.0", True, cap=9300,
        ),
        Source(
            "tweet_sentiment_en", "cardiffnlp/tweet_sentiment_multilingual", None, "train",
            "test", tweet_sentiment("en"), "sentiment", "en", "CC BY 3.0 + Twitter ToS",
            True, load_kwargs={**PARQUET, "data_dir": "english"},
        ),
        Source(
            "tweet_sentiment_fr", "cardiffnlp/tweet_sentiment_multilingual", None, "train",
            "test", tweet_sentiment("fr"), "sentiment", "fr", "CC BY 3.0 + Twitter ToS",
            True, load_kwargs={**PARQUET, "data_dir": "french"},
        ),
        Source(
            "go_emotions", "google-research-datasets/go_emotions", "raw", "train", None,
            go_emotions, "emotion", "en", "Apache-2.0", True, cap=20000,
            load=go_emotions_raters, group=lambda r: r["id"],
        ),
        Source(
            "mlma_fr", "nedjmaou/MLMA_hate_speech", None, "train", None, mlma("fr"),
            "offensive", "fr", "MIT (HF card)", True,
            load_kwargs={"data_files": "fr_dataset.csv"}, group=lambda r: r["tweet"],
        ),
        Source(
            "mlma_en", "nedjmaou/MLMA_hate_speech", None, "train", None, mlma("en"),
            "offensive", "en", "MIT (HF card)", True,
            load_kwargs={"data_files": "en_dataset_with_stop_words.csv"},
            group=lambda r: r["tweet"],
        ),
        Source(
            "textdetox_fr", "textdetox/multilingual_toxicity_dataset", None, "fr", None,
            textdetox("fr"), "offensive", "fr", "openrail++ (use restrictions)", False,
            group=lambda r: r["text"],
        ),
    ]
}  # fmt: skip
